global:
    scrape_interval: 5s
    evaluation_interval: 5s

scrape_configs:
    -   job_name: 'scheduler'
        static_configs:
            -   targets: [ 'host.docker.internal:8080' ]
    -   job_name: 'collector'
        metrics_path: '/actuator/prometheus'
        static_configs:
            -   targets: [ 'host.docker.internal:8081' ]
